# Generated by Django 3.2.2 on 2021-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='adj_close',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Adj Close'),
        ),
        migrations.AlterField(
            model_name='data',
            name='close',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Close'),
        ),
        migrations.AlterField(
            model_name='data',
            name='high',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='High'),
        ),
        migrations.AlterField(
            model_name='data',
            name='low',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Low'),
        ),
        migrations.AlterField(
            model_name='data',
            name='open',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Open'),
        ),
    ]
